/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author dam2
 */
public class Vista extends javax.swing.JFrame {

    /**
     * Creates new form Vista
     */
    public Vista() {
        initComponents();
        setNombres();
        
    }
    
    public void setNombres(){
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelVista = new javax.swing.JPanel();
        jLabelNombreVista = new javax.swing.JLabel();
        jLabelMarcaVista = new javax.swing.JLabel();
        jLabelEdadVista = new javax.swing.JLabel();
        jLabelPrecioVista = new javax.swing.JLabel();
        jLabelTipoVista = new javax.swing.JLabel();
        jLabelMuestraNombre = new javax.swing.JLabel();
        jLabelMuestraMarca = new javax.swing.JLabel();
        jLabelMuestraEdad = new javax.swing.JLabel();
        jLabelMuestraPrecio = new javax.swing.JLabel();
        jLabelMuestraTipo = new javax.swing.JLabel();
        jLabelFotoVista = new javax.swing.JLabel();
        jPanelBaseVista = new javax.swing.JPanel();
        jButtonAnterirorVista = new javax.swing.JButton();
        jLabelMostrandoVista = new javax.swing.JLabel();
        jLabelDeVista = new javax.swing.JLabel();
        jLabelMaximoCarrouselVista = new javax.swing.JLabel();
        jButtonSiguienteVista = new javax.swing.JButton();
        jButtonCancelFilterVista = new javax.swing.JButton();
        jPanelEdicion = new javax.swing.JPanel();
        jPanelFiltro = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelVista.setPreferredSize(new java.awt.Dimension(690, 320));

        jLabelNombreVista.setText("Nombre");

        jLabelMarcaVista.setText("Marca");

        jLabelEdadVista.setText("Edad");

        jLabelPrecioVista.setText("Precio");

        jLabelTipoVista.setText("Tipo");

        jLabelMuestraNombre.setText("jLabel1");

        jLabelMuestraMarca.setText("jLabel1");

        jLabelMuestraEdad.setText("jLabel2");

        jLabelMuestraPrecio.setText("jLabel3");

        jLabelMuestraTipo.setText("jLabel7");

        jLabelFotoVista.setText("FOTO");
        jLabelFotoVista.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 40, 5);
        flowLayout1.setAlignOnBaseline(true);
        jPanelBaseVista.setLayout(flowLayout1);

        jButtonAnterirorVista.setText("Anterior");
        jPanelBaseVista.add(jButtonAnterirorVista);

        jLabelMostrandoVista.setText("X");
        jPanelBaseVista.add(jLabelMostrandoVista);

        jLabelDeVista.setText(" de ");
        jPanelBaseVista.add(jLabelDeVista);

        jLabelMaximoCarrouselVista.setText("X");
        jPanelBaseVista.add(jLabelMaximoCarrouselVista);

        jButtonSiguienteVista.setText("Siguiente");
        jPanelBaseVista.add(jButtonSiguienteVista);

        jButtonCancelFilterVista.setText("Cancelar Filtro");

        javax.swing.GroupLayout jPanelVistaLayout = new javax.swing.GroupLayout(jPanelVista);
        jPanelVista.setLayout(jPanelVistaLayout);
        jPanelVistaLayout.setHorizontalGroup(
            jPanelVistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelVistaLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanelVistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelNombreVista)
                    .addComponent(jLabelMarcaVista)
                    .addComponent(jLabelEdadVista)
                    .addComponent(jLabelPrecioVista)
                    .addComponent(jLabelTipoVista))
                .addGap(18, 18, 18)
                .addGroup(jPanelVistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelMuestraTipo)
                    .addComponent(jLabelMuestraPrecio)
                    .addComponent(jLabelMuestraEdad)
                    .addComponent(jLabelMuestraMarca)
                    .addComponent(jLabelMuestraNombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelFotoVista, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83))
            .addComponent(jPanelBaseVista, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 690, Short.MAX_VALUE)
            .addGroup(jPanelVistaLayout.createSequentialGroup()
                .addGap(283, 283, 283)
                .addComponent(jButtonCancelFilterVista)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelVistaLayout.setVerticalGroup(
            jPanelVistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVistaLayout.createSequentialGroup()
                .addGroup(jPanelVistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelVistaLayout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addGroup(jPanelVistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelNombreVista)
                            .addComponent(jLabelMuestraNombre))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelVistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelMarcaVista)
                            .addComponent(jLabelMuestraMarca))
                        .addGap(11, 11, 11)
                        .addGroup(jPanelVistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelEdadVista, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelMuestraEdad))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelVistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelPrecioVista)
                            .addComponent(jLabelMuestraPrecio))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelVistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelTipoVista)
                            .addComponent(jLabelMuestraTipo)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelVistaLayout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jLabelFotoVista, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jPanelBaseVista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonCancelFilterVista)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanelEdicion.setPreferredSize(new java.awt.Dimension(690, 320));

        javax.swing.GroupLayout jPanelEdicionLayout = new javax.swing.GroupLayout(jPanelEdicion);
        jPanelEdicion.setLayout(jPanelEdicionLayout);
        jPanelEdicionLayout.setHorizontalGroup(
            jPanelEdicionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 690, Short.MAX_VALUE)
        );
        jPanelEdicionLayout.setVerticalGroup(
            jPanelEdicionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 321, Short.MAX_VALUE)
        );

        jPanelFiltro.setPreferredSize(new java.awt.Dimension(690, 320));

        javax.swing.GroupLayout jPanelFiltroLayout = new javax.swing.GroupLayout(jPanelFiltro);
        jPanelFiltro.setLayout(jPanelFiltroLayout);
        jPanelFiltroLayout.setHorizontalGroup(
            jPanelFiltroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 710, Short.MAX_VALUE)
        );
        jPanelFiltroLayout.setVerticalGroup(
            jPanelFiltroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 342, Short.MAX_VALUE)
        );

        jMenu1.setText("File");

        jMenuItem1.setText("jMenuItem1");
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("jMenuItem2");
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelFiltro, javax.swing.GroupLayout.DEFAULT_SIZE, 710, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanelEdicion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanelVista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelFiltro, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addComponent(jPanelEdicion, javax.swing.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanelVista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(11, 11, 11)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAnterirorVista;
    private javax.swing.JButton jButtonCancelFilterVista;
    private javax.swing.JButton jButtonSiguienteVista;
    private javax.swing.JLabel jLabelDeVista;
    private javax.swing.JLabel jLabelEdadVista;
    private javax.swing.JLabel jLabelFotoVista;
    private javax.swing.JLabel jLabelMarcaVista;
    private javax.swing.JLabel jLabelMaximoCarrouselVista;
    private javax.swing.JLabel jLabelMostrandoVista;
    private javax.swing.JLabel jLabelMuestraEdad;
    private javax.swing.JLabel jLabelMuestraMarca;
    private javax.swing.JLabel jLabelMuestraNombre;
    private javax.swing.JLabel jLabelMuestraPrecio;
    private javax.swing.JLabel jLabelMuestraTipo;
    private javax.swing.JLabel jLabelNombreVista;
    private javax.swing.JLabel jLabelPrecioVista;
    private javax.swing.JLabel jLabelTipoVista;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPanelBaseVista;
    private javax.swing.JPanel jPanelEdicion;
    private javax.swing.JPanel jPanelFiltro;
    private javax.swing.JPanel jPanelVista;
    // End of variables declaration//GEN-END:variables
}
